<?php
 
 return [
    'apartments' => 
        [
            "user_id" => 1,
            "title" => 'Villa bucchini 1',
            "description" => "Appartamento 1",
            "rooms" => 2,
            "bathrooms" => 1,
            "beds" => 2,
            "square_meters" => 80,
            "address" => "Via Roma 123",
            "latitude" => 41.89193,
            "longitude" => 12.51133,
            "image" => "https://picsum.photos/200/300",
            "visibility" => true,
        ],
        [
            "user_id" => 1,
            "title" => 'Villa scroti 3',
            "description" => "Appartamento 2",
            "rooms" => 2,
            "bathrooms" => 1,
            "beds" => 2,
            "square_meters" => 80,
            "address" => "Via Roma 123",
            "latitude" => 41.89193,
            "longitude" => 12.51133,
            "image" => "https://picsum.photos/200/300",
            "visibility" => true,
        ],
        [
            "user_id" => 1,
            "title" => 'Villa Sandra 3',
            "description" => "Appartamento 3",
            "rooms" => 2,
            "bathrooms" => 1,
            "beds" => 2,
            "square_meters" => 80,
            "address" => "Via Roma 123",
            "latitude" => 41.89193,
            "longitude" => 12.51133,
            "image" => "https://picsum.photos/200/300",
            "visibility" => true,
        ],
        [
            "user_id" => 2,
            "title" => 'Villa mirco 3',
            "description" => "Appartamento 4",
            "rooms" => 2,
            "bathrooms" => 1,
            "beds" => 2,
            "square_meters" => 80,
            "address" => "Via Roma 123",
            "latitude" => 41.89193,
            "longitude" => 12.51133,
            "image" => "https://picsum.photos/200/300",
            "visibility" => true,
        ],
        [
            "user_id" => 2,
            "title" => 'Villa Sara 3',
            "description" => "Appartamento 5",
            "rooms" => 2,
            "bathrooms" => 1,
            "beds" => 2,
            "square_meters" => 80,
            "address" => "Via Roma 123",
            "latitude" => 41.89193,
            "longitude" => 12.51133,
            "image" => "https://picsum.photos/200/300",
            "visibility" => true,
        ],
        [
            "user_id" => 2,
            "title" => 'Villa Michela 3',
            "description" => "Appartamento 6",
            "rooms" => 2,
            "bathrooms" => 1,
            "beds" => 2,
            "square_meters" => 80,
            "address" => "Via Roma 123",
            "latitude" => 41.89193,
            "longitude" => 12.51133,
            "image" => "https://picsum.photos/200/300",
            "visibility" => true,
        ],
        [
            "user_id" => 3,
            "title" => 'Villa Lucia 3',
            "description" => "Appartamento 7",
            "rooms" => 2,
            "bathrooms" => 1,
            "beds" => 2,
            "square_meters" => 80,
            "address" => "Via Roma 123",
            "latitude" => 41.89193,
            "longitude" => 12.51133,
            "image" => "https://picsum.photos/200/300",
            "visibility" => true,
        ],
        [
            "user_id" => 3,
            "title" => 'Villa Carmela 3',
            "description" => "Appartamento 8",
            "rooms" => 2,
            "bathrooms" => 1,
            "beds" => 2,
            "square_meters" => 80,
            "address" => "Via Roma 123",
            "latitude" => 41.89193,
            "longitude" => 12.51133,
            "image" => "https://picsum.photos/200/300",
            "visibility" => true,
        ],
        [
            "user_id" => 3,
            "title" => 'Villa Domizianal 3',
            "description" => "Appartamento 9",
            "rooms" => 2,
            "bathrooms" => 1,
            "beds" => 2,
            "square_meters" => 80,
            "address" => "Via Roma 123",
            "latitude" => 41.89193,
            "longitude" => 12.51133,
            "image" => "https://picsum.photos/200/300",
            "visibility" => true,
        ],
        [
            "user_id" => 3,
            "title" => 'Villa Peppa 3',
            "description" => "Appartamento 10",
            "rooms" => 2,
            "bathrooms" => 1,
            "beds" => 2,
            "square_meters" => 80,
            "address" => "Via Roma 123",
            "latitude" => 41.89193,
            "longitude" => 12.51133,
            "image" => "https://picsum.photos/200/300",
            "visibility" => true,
        ],
    ];